name: SimplyCasinoGames
api-version: 1.7.10
version: '1.0.0'
main: com.railwaycraft.simplycasinogames.SimplyCasinoGames
depend: [RWCEconomy]
commands:
  blackjack:
    usage: /blackjack <player> <tableNumber> [BuyIn]
  slots:
    usage: /slots <player> <BuyIn>